name: Python Selenium Script

on:
  push:
    branches:
      - main  # ou 'master' selon la branche sur laquelle tu travailles

jobs:
  selenium_job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        pip install -r requirements.txt

    - name: Run script
      run: |
        python3 script.py
      env:
        DISPLAY: :99  # Cela permet de faire tourner Chrome en mode headless
